name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  

    - name: Build Spring Boot JAR
      run: |
        cd back 
        ./mvnw clean package -DskipTests 

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: spring-boot-app
        path: back/target/*.jar 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
          context: ./back
          file: ./back/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/OC-Project-10-Back-end:latest  
