name: Angular C

on:
  push:
    branches:
      - main
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code                  
      uses: actions/checkout@v4
        
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
              cd front
              npm install

    - name: Run tests
      run: |
              cd front
              npm run test

      
    - name: Run Build
      run: |
              cd front
              npm run build
