name: Angular C

on:
  push:
    branches:
      - main
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code                  
      uses: actions/checkout@v4
        
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
              cd front
              npm install

    - name: Run tests
      run: |
              cd front
              npm run test

      
    - name: Run Build
      run: |
              cd front
              npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: remove node_modules to avoid docker build error
      run : |
              cd front
              rm -r node_modules
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oc-project-10-front-end:latest
          
